manifest:
  version: 0.7
  projects:
    - name: zephyr
      path: zephyr
      revision: main
 # DAC Driver
    - name: dac7578
      url: https://github.com/marcrickenbach/dac7578
      revision: main
      path: dac7578

  self:
    path: Terpsichore

  west:
    extra_modules:
      - boards
