/** ****************************************************************************
 * @brief Internal state machine events generated by LED.
 */

#ifndef FKMG_LED_SM_EVT_H
#define FKMG_LED_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum LED_SM_Evt_Sig{
    k_LED_SM_Evt_Sig_Beg,                           // Inclusive
    k_LED_SM_Evt_Sig_Min = k_LED_SM_Evt_Sig_Beg,    // Inclusive
    k_LED_SM_Evt_Sig_1st = k_LED_SM_Evt_Sig_Beg,    // Inclusive

	k_LED_SM_Evt_Sig_Init_Instance = k_LED_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_LED_ALLOW_SHUTDOWN
	k_LED_SM_Evt_Sig_Deinit_Instance,
    #endif
	k_LED_SM_Evt_Sig_Write,
	k_LED_SM_Evt_Sig_Clear,

    k_LED_SM_Evt_Sig_End,                           // Exclusive
    k_LED_SM_Evt_Sig_Max = k_LED_SM_Evt_Sig_End - 1,// Inclusive
    k_LED_SM_Evt_Sig_Lst = k_LED_SM_Evt_Sig_End - 1,// Inclusive
    k_LED_SM_Evt_Sig_Cnt = k_LED_SM_Evt_Sig_End
                         - k_LED_SM_Evt_Sig_Beg,	// Inclusive
	k_LED_SM_Evt_Sig_Ivd = k_LED_SM_Evt_Sig_End
};

/* Data signal k_LED_SM_Evt_Sig_Init_Instance can generate. */
struct LED_SM_Evt_Sig_Init_Instance{
    struct LED_Instance_Cfg cfg;
};

/* Data signal k_LED_SM_Sig_Convert can generate. */
struct LED_SM_Evt_Sig_Write{
    enum LED_Id row;
    uint8_t val;
};

/* Events (i.e. signal + signal's data if any) LED State Machine generates. */
struct LED_SM_Evt{
	enum LED_SM_Evt_Sig sig;
	union LED_SM_Evt_Data{
        struct LED_SM_Evt_Sig_Init_Instance     init_inst;
        struct LED_SM_Evt_Sig_Write             write;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_LED_SM_EVT_H */
